(module
  (type $bt  (func (result i32)))
  (type $ct  (cont $bt))
  (type $rt  (func (param i32) (result i32)))
  (type $rct (cont $rt))
  (tag $pick (result i32))
  (elem declare func $body)
  (func $body (result i32) (suspend $pick))
  ;; rerun(v): fresh cont, run body to the pick, then resume the captured cont with v
  (func $rerun (param $v i32) (result i32)
    (local $k (ref $rct))
    (block $on_pick (result (ref $rct))
      (resume $ct (on $pick $on_pick) (cont.new $ct (ref.func $body)))
      (return))
    (local.set $k)
    (resume $rct (local.get $v) (local.get $k)))
  (func $run (export "run") (result i32)
    (i32.add (call $rerun (i32.const 1)) (call $rerun (i32.const 2)))))
