(module
  (type $ft0 (func (result i32)))
  (type $ft1 (func (param i32) (result i32)))
  (type $ft_ii_d (func (param i32) (param i32) (result f64)))
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $proc_exit (param i32)))
  (import "wasi" "thread-spawn" (func $wasi_thread_spawn (param i32) (result i32)))
  (memory (export "memory") 65536 65536 shared)
  (global $heap_ptr (mut i32) (i32.const 1048576))
  (global $arena_ptr (mut i32) (i32.const 1048576))
  (func $alloc (param $size i32) (result i32)(local $ptr i32)(local.set $ptr (global.get $heap_ptr))(global.set $heap_ptr (i32.add (local.get $ptr)(i32.and (i32.add (local.get $size)(i32.const 7))(i32.const -8))))(local.get $ptr)(br_if 0 (i32.ge_u (global.get $heap_ptr)(local.get $ptr)))(unreachable))
  (table $fns 2 funcref)
  (elem $fns (i32.const 0) $to_sample $main)
  (global $to_sample_idx i32 (i32.const 0))
  (global $main_idx i32 (i32.const 1))
  (data (i32.const 4096) "\00\00\00\00\00\00\00\00")
  (global $to_sample i32 (i32.const 4096))
  (data (i32.const 4104) "\01\00\00\00\00\00\00\00")
  (global $main i32 (i32.const 4104))
  ;; fn to_sample reason: inferred from float literal
  (func $to_sample (param $__state i32) (param $n i32) (result f64) (local $state_tmp i32) (local $variant_tmp i32) (local $record_tmp i32) (local $scrut_tmp i32) (local $callee_closure i32) (local $alloc_size i32) (local $loop_i i32)
    (local.get $n)
    (i32.const 0)
    (i32.gt_s)
    (if (result f64)
      (then
    (f64.const 0.50000000000000000)
      )
      (else
    (f64.const 0.0)
      ))
  )
  ;; fn main reason: return of fn
  (func $main (param $__state i32) (result f64) (local $state_tmp i32) (local $variant_tmp i32) (local $record_tmp i32) (local $scrut_tmp i32) (local $callee_closure i32) (local $alloc_size i32) (local $loop_i i32) (local $call_17 i32)
    (global.get $to_sample)
    (local.set $call_17)
    (local.get $call_17)
    (i32.const 1)
    (local.get $call_17) (i32.load offset=0)
    (return_call_indirect (type $ft_ii_d))
  )
  (func $_start
    (call $main (global.get $main))
    (call $proc_exit)
  )
  (export "_start" (func $_start))
  (func $wasi_thread_start (param $tid i32) (param $start_arg i32)
    (local $closure_ptr i32)
    (local $result i32)
    (local $done_addr i32)
    (local $nc i32)
    ;; start_arg IS the closure pointer (Stage 3 substrate collapse)
    (local.set $closure_ptr (local.get $start_arg))
    ;; Invoke closure: push __state = closure_ptr, then call_indirect via fn_idx@0
    (local.get $closure_ptr)
    (local.get $closure_ptr) (i32.load offset=0)
    (call_indirect (type $ft1))
    (local.set $result)
    ;; done_addr = closure_ptr + 8 + 4 * capture_count
    (local.set $nc (i32.load offset=4 (local.get $closure_ptr)))
    (local.set $done_addr
      (i32.add (local.get $closure_ptr)
        (i32.add (i32.const 8) (i32.mul (i32.const 4) (local.get $nc)))))
    ;; Store result at done_addr + 4
    (i32.store offset=4 (local.get $done_addr) (local.get $result))
    ;; Atomic.store done = 1
    (i32.atomic.store (local.get $done_addr) (i32.const 1))
    ;; Notify any waiters on this done flag
    (drop (memory.atomic.notify (local.get $done_addr) (i32.const -1)))
  )
  (export "wasi_thread_start" (func $wasi_thread_start))
)
