#!/usr/bin/env bash
# ═══ Mentl first-light march — the binary-arbiter gate in ONE command ════════
# boot → m2 → m3 (→ m4), with structured trap / probe reporting, so a
# diagnostic cycle is a single invocation instead of a hand-typed pipeline.
# Pairs with tools/verify.sh (micros + census, stamped green).
#
#   bash tools/march.sh             # boot → m2 → m3, ASSERT the fixpoint ratchet
#   bash tools/march.sh --fixpoint  # force the m4 leg even on a clean m2 == m3
#
# The ratchet arbitrates ITSELF: m2 == m3 is the fixpoint; on m2 ≠ m3 the march
# runs the m4 leg automatically and rules TRANSITION (m3 == m4 — an emit/import
# change crossed one generation; re-pin boot from m3) vs BROKEN (m3 ≠ m4). The
# m2 leg reads the ONE keyed boot(wheel) artifact (wt_m2_ensure, .build/m2cache
# — shared with verify's census and march-gate), so gates never re-derive the
# same ~13-minute compile.
#
# Artifacts land in .build/march (luks-backed, per PLAN §8), NEVER /tmp — /tmp is
# RAM-backed tmpfs here, and a 50MB objdump + 12MB m2.wat × repeated runs OOMs the
# box (it did, 2026-06-30). .build is on disk; override with MARCH_OUT=<dir>.
set -u
cd "$(dirname "$0")/.." || exit 2
source "$(dirname "$0")/wt-env.sh"   # WT, WT_RUN_FLAGS, W2W — the one home
OUT="${MARCH_OUT:-$(pwd)/.build/march}"; mkdir -p "$OUT"
WHEEL="$OUT/wheel.mn"
# Boot from the PINNED FIXPOINT WHEEL (boot/mentl.wasm — boot/PROVENANCE.md).
# m2 := boot(wheel) is wheel-emitted, so m2 == m3 IS the fixed point. The
# hand-WAT seed is DELETED (7401c4b); the cold-ladder recipe lives at tag
# first-light (band J archaeology).
FIXPOINT=0
for a in "$@"; do case "$a" in
  --fixpoint)  FIXPOINT=1 ;;
  *) echo "march: unknown arg '$a'" >&2; exit 2 ;;
esac; done

# trap signatures: a wasmtime runtime trap OR a name-section frame of the known
# trap site. Empty match = the gate is GREEN.
trap_lines() { grep -nE 'out of bounds|wasm trap|undefined element|unreachable|op_each_handler_yield' "$1" 2>/dev/null; }
# timeout execs a real binary (not the wt_run function), so it uses the same
# constants wt_run projects from — WT + WT_RUN_FLAGS, the one home (wt-env.sh).
# 9000s: pass-2 measured ~2h-class on the seed-idiom m2 (2026-07-05 —
# ~300 wheel-lines/min, ~19MB/min; the profile is Hβ.m2.compile-alloc-profile,
# instantiate tree-clones the prime suspect). The old 480s cap predates the
# union_row-divergence fix, when every long run meant the infinite loop.
gen() { timeout 9000 "$WT" run -D coredump="$OUT/$(basename "$2" .wat).coredump" "${WT_RUN_FLAGS[@]}" "$1" < "$WHEEL" > "$2" 2> "$3"; }  # coredump: one trap buys the whole heap autopsy (face 7 lesson)  # gen <wasm> <out.wat> <out.err>

# WABT disassembly, cached on the wasm's mtime (objdump on 1.7MB is slow; the
# 500k-line dump is reused across runs until m2.wasm is rebuilt). PLAN §8: pin the
# trap with the binary toolkit, NEVER grep the minified emit.
disasm() {  # disasm <in.wasm> → echoes the cached .dis path
  local w="$1" d="${1%.wasm}.dis"
  [ -f "$d" ] && [ "$d" -nt "$w" ] || wasm-objdump -d "$w" > "$d" 2>/dev/null
  echo "$d"
}
# ── emit_provenance — the pin's MECHANICAL facts, machine-written ────
# The march HOLDS the sha, the verdict, the generation, the line count
# and the census at the moment it repins; a human retyping any of them
# later is the fabrication class (caught live twice — a sha tail
# completed from memory, CLAUDE.md ⊕). So the march writes them, read
# from the artifact it just copied, and the AUTHOR writes only the
# narrative. The unwritten narrative is a literal placeholder, so an
# unblessed pin is MECHANICALLY visible (doc-truth refuses while it
# stands) instead of resting on the discipline of remembering.
# The first executed rung of ledger-as-projection (PLAN §7's own
# destiny: state as a projection, never a hand-kept prose ledger).
emit_provenance() {  # emit_provenance <gen> <verdict> <lines> <census>
  local gen="$1" verdict="$2" lines="$3" census="$4" sha block tmp
  sha=$(sha256sum boot/mentl.wasm | awk '{print $1}')
  block=$(cat <<EOF
- source: ‹NARRATIVE UNWRITTEN — replace this line: what landed and why,
  the §7 ledger entry of the same name carrying the arc›
- boot/mentl.wasm  sha256 $sha
  ($verdict; re-pinned from $gen per march.sh — $lines lines, census $census)
- generated by: ${verdict%% *} (prior pin follows)

---
EOF
)
  tmp=$(mktemp)
  awk -v blk="$block" '
    { print }
    !done && /^Provenance, self-confirmed at pin time:$/ { print ""; print blk; done=1 }
  ' boot/PROVENANCE.md > "$tmp" && mv "$tmp" boot/PROVENANCE.md
  echo "· PROVENANCE: mechanical block written (sha, verdict, lines, census — read from the artifact)"
  echo "  the narrative line is a placeholder; doc-truth refuses the pin until it is written"
}

pin_trap() {  # pin_trap <wasm> <err> — auto-disassemble the trap site from the backtrace
  local w="$1" e="$2" fn dis
  fn=$(grep -oE '<unknown>!\S+' "$e" 2>/dev/null | head -1 | sed 's/.*!//')
  [ -z "$fn" ] && fn=$(grep -oE 'op_[a-z_]+' "$e" 2>/dev/null | head -1)
  [ -z "$fn" ] && { echo "  (no named trap frame to pin)"; return; }
  dis=$(disasm "$w")
  echo "  ── WABT trap pin: <$fn> around its call_indirect ──"
  awk -v fn="<$fn>:" '
    index($0,fn){p=1}
    p{n++; print "    " $0}
    p && /call_indirect/{c++}
    p && c>=1 && n>4{exit}
    p && n>34{exit}' "$dis" | grep -E 'load|store|local|global|call|func\[' | head -18
}

# ── wheel input: `find`, NOT `cat src/*.mn` (PLAN §6 — cat omits backends/) ──
{ find lib -name '*.mn' -not -path '*/tutorial/*' | sort | xargs cat
  find src -name '*.mn' | sort | xargs cat; } > "$WHEEL"
echo "wheel: $(wc -l < "$WHEEL") lines"

BOOT=boot/mentl.wasm
[ -f "$BOOT" ] || { echo "✗ no $BOOT (boot/PROVENANCE.md)"; exit 1; }
echo "✓ boot: $BOOT (the pinned fixpoint wheel)"

# ── m2: the boot compiler compiles the wheel ──
# Reads the ONE keyed boot(wheel) artifact (wt_m2_ensure — shared with
# verify's census and march-gate; .build/m2cache): instant when another
# gate already compiled this exact state.
if C=$(wt_m2_ensure); then
  wt_m2_place "$C" "$OUT"; m2rc=0
  echo "m2: boot(wheel) via $C — $(wc -l < "$OUT/m2.wat") lines (key $(cut -c1-12 "$C/key"))"
else
  echo "✗ m2 generation TRAPPED (see $WT_M2CACHE/m2.err):"; trap_lines "$WT_M2CACHE/m2.err" | head -6; exit 1
fi
echo "✓ m2 assembles ($(stat -c%s "$OUT/m2.wasm") bytes)"

if [ -n "${PROBE:-}" ]; then
  # closure record = [fn_ptr@0][nc@4][caps..][evs..], alloc = 8 + 4*(nc+ne).
  SZ=$(grep -oE "\(i32.const ([0-9]+)\)\(i32.add\)\(global.set \\\$heap_ptr\)\(local.get \\\$state_tmp\)\(global.get \\\$${PROBE}_idx\)" "$OUT/m2.wat" | grep -oE 'const [0-9]+' | grep -oE '[0-9]+' | head -1)
  NC=$(grep -oE "${PROBE}_idx\)\(i32.store offset=0\)\(local.get \\\$state_tmp\)\(i32.const [0-9]+\)" "$OUT/m2.wat" | grep -oE 'const [0-9]+' | grep -oE '[0-9]+' | head -1)
  if [ -n "$SZ" ]; then echo "  ${PROBE} closure: ${SZ}B frame, nc=${NC} caps, ne=$(( (SZ-8)/4 - ${NC:-0} )) evs"
  else echo "  ${PROBE} closure: <not found in m2.wat>"; fi
fi

# ── m3: m2 compiles the wheel — THE GATE (the trapping lambda executes here) ──
gen "$OUT/m2.wasm" "$OUT/m3.wat" "$OUT/m3.err"; m3rc=$?
echo "m3: exit=$m3rc, $(wc -l < "$OUT/m3.wat" 2>/dev/null) lines, census=$(grep -cE 'E_[A-Za-z]+ error' "$OUT/m3.err" 2>/dev/null)"
TRAP=$(trap_lines "$OUT/m3.err")
if [ -n "$TRAP" ]; then
  echo "✗ GATE: m3 TRAPPED —"; echo "$TRAP" | head -4
  pin_trap "$OUT/m2.wasm" "$OUT/m3.err"
else
  echo "✓ GATE: m3 clean (no trap)"
fi

# ── the FIXPOINT RATCHET ──
# m2 and m3 are BOTH wheel-emitted, so m2 == m3 is the fixed point —
# asserted on every run (the ratchet law: every wheel change holds
# m_n == m_{n+1}). --fixpoint extends the chain one more generation (m4)
# for the paranoid triple.
fixok=1; m4done=0
# SIZE-GUARD the compare (the empty-wat trap: two empty legs diff equal and a
# gate that cannot fail reads as a fixpoint — 2026-07-22's own lesson).
if [ ! -s "$OUT/m2.wat" ] || [ ! -s "$OUT/m3.wat" ]; then
  echo "✗ SIZE-GUARD: an empty wat leg (m2=$(wc -c < "$OUT/m2.wat" 2>/dev/null)B m3=$(wc -c < "$OUT/m3.wat" 2>/dev/null)B) — no verdict from empties"
  fixok=0
elif [ "$m3rc" = 0 ]; then
  if diff -q "$OUT/m2.wat" "$OUT/m3.wat" >/dev/null 2>&1; then
    echo "✓✓ FIXED POINT holds: m2 == m3"
    if [ "${MARCH_REPIN:-0}" = 1 ]; then
      cp "$OUT/m2.wasm" boot/mentl.wasm
      echo "· REPIN (clean): boot ← m2  sha256 $(sha256sum boot/mentl.wasm | cut -c1-16)…"
      emit_provenance m2 "CLEAN m2 == m3" \
        "$(wc -l < "$OUT/m2.wat" 2>/dev/null)" \
        "$(grep -cE 'E_[A-Za-z]+ error' "$OUT/m3.err" 2>/dev/null)"
    fi
  else
    # THE TRANSITION FORM — native, never hand-driven. A change to the wheel's
    # own EMIT or import surface crosses one generation: m2 is the OLD emit
    # rendering the new source, m3 the NEW emit — different bytes by design
    # (PLAN §6's original rule, resurfacing whenever the emit itself moves).
    # The fixpoint then lands at m3 == m4, and blessing the wrong generation
    # (m2) is the classic trusting-trust mistake — so the march arbitrates
    # itself instead of leaving the m4 leg to a human.
    echo "· RATCHET: m2 ≠ m3 ($(diff "$OUT/m2.wat" "$OUT/m3.wat" 2>/dev/null | grep -c '^[<>]') diff lines) — testing the TRANSITION form (m3 == m4)"
    if "${W2W[@]}" "$OUT/m3.wat" -o "$OUT/m3.wasm" 2> "$OUT/m3w.err"; then
      gen "$OUT/m3.wasm" "$OUT/m4.wat" "$OUT/m4.err"; m4rc=$?; m4done=1
      echo "m4: exit=$m4rc, $(wc -l < "$OUT/m4.wat" 2>/dev/null) lines"
      if [ "$m4rc" = 0 ] && diff -q "$OUT/m3.wat" "$OUT/m4.wat" >/dev/null 2>&1; then
        echo "✓✓ TRANSITION: m3 == m4 — the NEW wheel reproduces itself; the m2/m3 diff was the emit change crossing one generation."
        if [ "${MARCH_REPIN:-0}" = 1 ]; then
          cp "$OUT/m3.wasm" boot/mentl.wasm
          echo "· REPIN (transition): boot ← m3  sha256 $(sha256sum boot/mentl.wasm | cut -c1-16)…  (blessing m2 here is the trusting-trust mistake this arbitration exists to prevent)"
          emit_provenance m3 "TRANSITION m3 == m4" \
            "$(wc -l < "$OUT/m3.wat" 2>/dev/null)" \
            "$(grep -cE 'E_[A-Za-z]+ error' "$OUT/m3.err" 2>/dev/null)"
        else
          echo "   Re-pin to bless: cp $OUT/m3.wasm boot/mentl.wasm  (or rerun with MARCH_REPIN=1; then update boot/PROVENANCE.md — the recipe is in that file)"
        fi
      else
        echo "✗✗ BROKEN: m3 ≠ m4 ($(diff "$OUT/m3.wat" "$OUT/m4.wat" 2>/dev/null | grep -c '^[<>]') diff lines; m4 exit=$m4rc) — genuine non-reproduction, not a transition"
        fixok=0
      fi
    else
      echo "✗ m3 wat2wasm FAILED (transition leg cannot run):"; head -5 "$OUT/m3w.err"; fixok=0
    fi
  fi
fi
if [ "$FIXPOINT" = 1 ] && [ "$m3rc" = 0 ] && [ "$m4done" = 0 ]; then
  if "${W2W[@]}" "$OUT/m3.wat" -o "$OUT/m3.wasm" 2>/dev/null; then
    gen "$OUT/m3.wasm" "$OUT/m4.wat" "$OUT/m4.err"; m4rc=$?
    if [ "$m4rc" = 0 ] && diff -q "$OUT/m3.wat" "$OUT/m4.wat" >/dev/null 2>&1; then
      echo "✓✓ FIRST LIGHT: m3 == m4 (fixed point)"
    else
      echo "· m3 ≠ m4 ($(diff "$OUT/m3.wat" "$OUT/m4.wat" 2>/dev/null | grep -c '^[<>]') diff lines; m4 exit=$m4rc)"
      fixok=0
    fi
  fi
fi
[ -z "$TRAP" ] && [ "$m3rc" = 0 ] && [ "$fixok" = 1 ]
